feat: add events API
onelogin/onelogin-go-sdk pull request #53
Opened 2022-05-18 07:18 UTC by ebarti

2022-05-19 09:32 UTC, ebarti commented
@eriktalvi kindly review whenever you have time

2022-05-20 20:24 UTC, eriktalvi requested changes

2022-05-20 20:24 UTC, eriktalvi commented on pkg/services/events/v1.go
> +	"fmt"
```suggestion
	"fmt"

```

2022-05-20 20:24 UTC, eriktalvi commented on pkg/services/events/model.go
> +	EventTypeIds         *int32     `json:"event_type_ids,omitempty"`
```suggestion
	EventTypeIDs         *int32     `json:"event_type_ids,omitempty"`
```

2022-06-02 13:16 UTC, closed without merging